export const EventTypes = {
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_UPDATED: 'SESSION_UPDATED',
  SESSION_DELETED: 'SESSION_DELETED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_STREAM_UPDATE: 'MESSAGE_STREAM_UPDATE',
  TOOL_CALLED: 'TOOL_CALLED',
  TOOL_APPROVED: 'TOOL_APPROVED',
  TOOL_REJECTED: 'TOOL_REJECTED',
  TOOL_COMPLETED: 'TOOL_COMPLETED',
  MODEL_CHANGED: 'MODEL_CHANGED',
  AGENT_CHANGED: 'AGENT_CHANGED',
  PROVIDER_STATUS_CHANGED: 'PROVIDER_STATUS_CHANGED',
  AGENT_STEP_COMPLETED: 'AGENT_STEP_COMPLETED',
  AGENT_ERROR: 'AGENT_ERROR',
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];
